package haproxy

import (
	"fmt"
	"net"
	"os"
	"os/exec"
	"strings"

	"github.com/carmendata/proxyctl/internal/config"
)

// Manager handles HAProxy configuration generation
type Manager struct {
	ConfigPath string // Path to haproxy.cfg
}

// NewManager creates a new HAProxy manager
func NewManager() *Manager {
	return &Manager{
		ConfigPath: "/etc/haproxy/haproxy.cfg",
	}
}

// GenerateConfig generates HAProxy configuration from v2 config
func (m *Manager) GenerateConfig(cfg *config.Config) error {
	if cfg.Proxy == nil || !cfg.Proxy.Enabled {
		return fmt.Errorf("proxy configuration is not enabled")
	}

	var haproxyConfig string
	var err error

	switch cfg.Proxy.Mode {
	case "egress":
		haproxyConfig, err = m.generateEgressConfig(cfg)
	case "ingress":
		haproxyConfig, err = m.generateIngressConfig(cfg)
	default:
		return fmt.Errorf("invalid proxy mode: %s", cfg.Proxy.Mode)
	}

	if err != nil {
		return fmt.Errorf("failed to generate config: %w", err)
	}

	// Validate configuration
	if err := m.validateConfig(haproxyConfig); err != nil {
		return fmt.Errorf("generated config is invalid: %w", err)
	}

	// Write configuration
	if err := os.WriteFile(m.ConfigPath, []byte(haproxyConfig), 0644); err != nil {
		return fmt.Errorf("failed to write config: %w", err)
	}

	return nil
}

// generateEgressConfig generates configuration for egress transparent proxy
func (m *Manager) generateEgressConfig(cfg *config.Config) (string, error) {
	if cfg.Proxy.Type != "transparent" {
		return "", fmt.Errorf("egress mode requires type 'transparent'")
	}

	if cfg.Proxy.Intercept == nil {
		return "", fmt.Errorf("egress transparent proxy requires intercept configuration")
	}

	// Resolve bind interface to IP address
	bindIP, err := m.resolveInterfaceIP(cfg.Interfaces, cfg.Proxy.Bind.Interface)
	if err != nil {
		return "", fmt.Errorf("failed to resolve bind interface: %w", err)
	}

	var sb strings.Builder

	// Global section
	sb.WriteString("# HAProxy Configuration - Transparent Egress Proxy\n")
	sb.WriteString("# Generated by proxyctl v2.0\n\n")
	sb.WriteString("global\n")
	sb.WriteString("    log /dev/log local0\n")
	sb.WriteString("    log /dev/log local1 notice\n")
	sb.WriteString("    chroot /var/lib/haproxy\n")
	sb.WriteString("    stats socket /run/haproxy/admin.sock mode 660 level admin\n")
	sb.WriteString("    stats timeout 30s\n")
	sb.WriteString("    user haproxy\n")
	sb.WriteString("    group haproxy\n")
	sb.WriteString("    daemon\n\n")

	// Default section
	sb.WriteString("defaults\n")
	sb.WriteString("    log     global\n")
	sb.WriteString("    mode    tcp\n")
	sb.WriteString("    option  tcplog\n")
	sb.WriteString("    option  dontlognull\n")
	sb.WriteString("    timeout connect 5000\n")
	sb.WriteString("    timeout client  50000\n")
	sb.WriteString("    timeout server  50000\n\n")

	// Frontend section - transparent TCP proxy
	sb.WriteString("# Transparent TCP Proxy Frontend\n")
	sb.WriteString("frontend transparent_proxy\n")
	sb.WriteString(fmt.Sprintf("    bind %s:%d transparent\n", bindIP, cfg.Proxy.Bind.Port))
	sb.WriteString("    mode tcp\n")
	sb.WriteString("    option tcplog\n")

	// Add custom logging if configured
	if cfg.Proxy.Logging != nil && cfg.Proxy.Logging.Enabled {
		sb.WriteString(fmt.Sprintf("    log-format \"%s\"\n", m.getLogFormat(cfg.Proxy.Logging.Format)))
	}

	sb.WriteString("    default_backend transparent_backend\n\n")

	// Backend section - use original destination
	sb.WriteString("# Transparent Backend - Forwards to Original Destination\n")
	sb.WriteString("backend transparent_backend\n")
	sb.WriteString("    mode tcp\n")
	sb.WriteString("    option tcplog\n")
	sb.WriteString("    # Use original destination (requires TPROXY)\n")
	sb.WriteString("    source 0.0.0.0 usesrc clientip\n")
	sb.WriteString("    server loopback 0.0.0.0:0 check inter 1000\n\n")

	// Stats page (optional)
	sb.WriteString("# Stats Page\n")
	sb.WriteString("listen stats\n")
	sb.WriteString("    bind *:9000\n")
	sb.WriteString("    mode http\n")
	sb.WriteString("    stats enable\n")
	sb.WriteString("    stats uri /stats\n")
	sb.WriteString("    stats refresh 30s\n")
	sb.WriteString("    stats show-node\n")
	sb.WriteString("    stats show-legends\n\n")

	return sb.String(), nil
}

// generateIngressConfig generates configuration for ingress reverse proxy
func (m *Manager) generateIngressConfig(cfg *config.Config) (string, error) {
	if cfg.Proxy.Type != "reverse" {
		return "", fmt.Errorf("ingress mode requires type 'reverse'")
	}

	if cfg.Proxy.Backends == nil {
		return "", fmt.Errorf("ingress reverse proxy requires backends configuration")
	}

	// Resolve bind interface to IP address
	bindIP, err := m.resolveInterfaceIP(cfg.Interfaces, cfg.Proxy.Bind.Interface)
	if err != nil {
		return "", fmt.Errorf("failed to resolve bind interface: %w", err)
	}

	var sb strings.Builder

	// Global section
	sb.WriteString("# HAProxy Configuration - Reverse Ingress Proxy\n")
	sb.WriteString("# Generated by proxyctl v2.0\n\n")
	sb.WriteString("global\n")
	sb.WriteString("    log /dev/log local0\n")
	sb.WriteString("    log /dev/log local1 notice\n")
	sb.WriteString("    chroot /var/lib/haproxy\n")
	sb.WriteString("    stats socket /run/haproxy/admin.sock mode 660 level admin\n")
	sb.WriteString("    stats timeout 30s\n")
	sb.WriteString("    user haproxy\n")
	sb.WriteString("    group haproxy\n")
	sb.WriteString("    daemon\n")

	// Add SSL configuration if enabled
	if cfg.Proxy.SSL != nil && cfg.Proxy.SSL.Enabled {
		sb.WriteString("    # SSL Configuration\n")
		sb.WriteString("    ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384\n")
		sb.WriteString("    ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets\n")
	}
	sb.WriteString("\n")

	// Default section
	sb.WriteString("defaults\n")
	sb.WriteString("    log     global\n")
	sb.WriteString("    mode    http\n")
	sb.WriteString("    option  httplog\n")
	sb.WriteString("    option  dontlognull\n")
	sb.WriteString("    option  forwardfor\n")
	sb.WriteString("    timeout connect 5000\n")
	sb.WriteString("    timeout client  50000\n")
	sb.WriteString("    timeout server  50000\n\n")

	// Frontend section
	sb.WriteString("# Reverse Proxy Frontend\n")
	sb.WriteString("frontend http_front\n")

	// Bind with SSL if configured
	if cfg.Proxy.SSL != nil && cfg.Proxy.SSL.Enabled {
		sb.WriteString(fmt.Sprintf("    bind %s:%d ssl crt %s\n", bindIP, cfg.Proxy.Bind.Port, cfg.Proxy.SSL.CertDir))
	} else {
		sb.WriteString(fmt.Sprintf("    bind %s:%d\n", bindIP, cfg.Proxy.Bind.Port))
	}

	sb.WriteString("    mode http\n")
	sb.WriteString("    option httplog\n")

	// Add custom logging if configured
	if cfg.Proxy.Logging != nil && cfg.Proxy.Logging.Enabled {
		sb.WriteString(fmt.Sprintf("    log-format \"%s\"\n", m.getLogFormat(cfg.Proxy.Logging.Format)))
	}

	sb.WriteString("    default_backend app_backend\n\n")

	// Backend section
	sb.WriteString("# Backend Servers\n")
	sb.WriteString("backend app_backend\n")
	sb.WriteString("    mode http\n")
	sb.WriteString("    option httplog\n")
	sb.WriteString("    option forwardfor\n")

	// Load balance algorithm
	loadBalance := cfg.Proxy.Backends.LoadBalance
	if loadBalance == "" {
		loadBalance = "roundrobin"
	}
	sb.WriteString(fmt.Sprintf("    balance %s\n", loadBalance))

	// Health check configuration
	if cfg.Proxy.Backends.HealthCheck != nil && cfg.Proxy.Backends.HealthCheck.Enabled {
		hc := cfg.Proxy.Backends.HealthCheck
		sb.WriteString(fmt.Sprintf("    option httpchk %s %s\n", hc.Method, hc.Path))
		sb.WriteString(fmt.Sprintf("    timeout check %s\n", hc.Timeout))
	}

	sb.WriteString("\n")

	// Backend servers
	for i, server := range cfg.Proxy.Backends.Servers {
		serverLine := fmt.Sprintf("    server backend%d %s:%d", i+1, server.IP, server.Port)

		// Add weight if specified
		if server.Weight > 0 {
			serverLine += fmt.Sprintf(" weight %d", server.Weight)
		}

		// Add health check if enabled
		if cfg.Proxy.Backends.HealthCheck != nil && cfg.Proxy.Backends.HealthCheck.Enabled {
			hc := cfg.Proxy.Backends.HealthCheck
			serverLine += fmt.Sprintf(" check inter %s", hc.Interval)
		}

		sb.WriteString(serverLine + "\n")
	}
	sb.WriteString("\n")

	// Stats page
	sb.WriteString("# Stats Page\n")
	sb.WriteString("listen stats\n")
	sb.WriteString("    bind *:9000\n")
	sb.WriteString("    mode http\n")
	sb.WriteString("    stats enable\n")
	sb.WriteString("    stats uri /stats\n")
	sb.WriteString("    stats refresh 30s\n")
	sb.WriteString("    stats show-node\n")
	sb.WriteString("    stats show-legends\n\n")

	return sb.String(), nil
}

// resolveInterfaceIP resolves a logical interface name to its IP address
func (m *Manager) resolveInterfaceIP(interfaces config.InterfacesConfig, logicalName string) (string, error) {
	physicalName, ok := interfaces[logicalName]
	if !ok {
		return "", fmt.Errorf("interface '%s' not found in configuration", logicalName)
	}

	// Special case for loopback
	if logicalName == "loopback" || physicalName == "lo" {
		return "127.0.0.1", nil
	}

	// Get interface
	iface, err := net.InterfaceByName(physicalName)
	if err != nil {
		return "", fmt.Errorf("interface '%s' not found on system: %w", physicalName, err)
	}

	// Get addresses
	addrs, err := iface.Addrs()
	if err != nil {
		return "", fmt.Errorf("failed to get addresses for interface '%s': %w", physicalName, err)
	}

	// Find first IPv4 address
	for _, addr := range addrs {
		if ipNet, ok := addr.(*net.IPNet); ok {
			if ip := ipNet.IP.To4(); ip != nil {
				return ip.String(), nil
			}
		}
	}

	return "", fmt.Errorf("no IPv4 address found for interface '%s'", physicalName)
}

// getLogFormat returns the HAProxy log format string
func (m *Manager) getLogFormat(format string) string {
	switch format {
	case "json":
		return `{"time":"%t","client":"%ci","frontend":"%f","backend":"%b","server":"%s","status":%ST,"bytes":%B,"duration":%Tt}`
	case "combined":
		return `%ci:%cp [%t] %ft %b/%s %Tw/%Tc/%Tt %B %ts %ac/%fc/%bc/%sc/%rc %sq/%bq`
	default:
		// Default to combined format
		return `%ci:%cp [%t] %ft %b/%s %Tw/%Tc/%Tt %B %ts %ac/%fc/%bc/%sc/%rc %sq/%bq`
	}
}

// validateConfig validates HAProxy configuration syntax
func (m *Manager) validateConfig(configContent string) error {
	// Write to temporary file
	tmpFile, err := os.CreateTemp("", "haproxy-*.cfg")
	if err != nil {
		return fmt.Errorf("failed to create temp file: %w", err)
	}
	defer os.Remove(tmpFile.Name())
	defer tmpFile.Close()

	if _, err := tmpFile.WriteString(configContent); err != nil {
		return fmt.Errorf("failed to write temp file: %w", err)
	}

	// Validate with haproxy -c
	cmd := exec.Command("haproxy", "-c", "-f", tmpFile.Name())
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("validation failed: %w\nOutput: %s", err, string(output))
	}

	return nil
}

// Reload reloads HAProxy service
func (m *Manager) Reload() error {
	cmd := exec.Command("systemctl", "reload", "haproxy")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to reload haproxy: %w (output: %s)", err, string(output))
	}
	return nil
}

// Restart restarts HAProxy service
func (m *Manager) Restart() error {
	cmd := exec.Command("systemctl", "restart", "haproxy")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to restart haproxy: %w (output: %s)", err, string(output))
	}
	return nil
}

// Enable enables HAProxy service
func (m *Manager) Enable() error {
	cmd := exec.Command("systemctl", "enable", "haproxy")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to enable haproxy: %w (output: %s)", err, string(output))
	}
	return nil
}

// GetStatus returns HAProxy service status
func (m *Manager) GetStatus() (string, error) {
	cmd := exec.Command("systemctl", "status", "haproxy")
	output, err := cmd.CombinedOutput()
	// Note: systemctl status returns non-zero if service is not running
	// We still want to return the output
	return string(output), err
}
